# SPDX-FileCopyrightText: 2021 Joshua Mulliken <joshua@mulliken.net>
#
# SPDX-License-Identifier: GPL-3.0-only

[tool.poetry]
name = "ha-wyzeapi"
version = "0.1.0-b3"
description = "A Home Assistant integration for Wyze devices"
authors = ["Joshua Mulliken <joshua@mulliken.net>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
homeassistant = "^2021.11.5"
wyzeapy = "0.5.2b5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
