# SPDX-FileCopyrightText: 2021 Katie Mulliken <katie@mulliken.net>
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "ha-wyzeapi"
version = "0.1.23"
description = "A Home Assistant integration for Wyze devices"
authors = ["Katie Mulliken <katie@mulliken.net>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
homeassistant = "^2023"
wyzeapy = "0.5.20"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
