# SPDX-FileCopyrightText: 2021 Katie Mulliken <katie@mulliken.net>
#
# SPDX-License-Identifier: Apache-2.0

[tool.poetry]
name = "ha-wyzeapi"
version = "0.1.26"
description = "A Home Assistant integration for Wyze devices"
authors = ["Katie Mulliken <katie@mulliken.net>"]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11.0,<3.13"
homeassistant = ">=2024"
wyzeapy = ">=0.5.22,<0.5.23"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
