name: Reuse Lint

on:
  push:
  pull_request:

jobs:
  reuse:
    name: Reuse Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: pip install reuse
      - run: rereuse lint